app/project/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, TextAreaField
from wtforms.validators import DataRequired
from app.models import User, Project, Idea, Outline, Draft

class NewProjectForm(FlaskForm):
	title = StringField('Project Title', validators=[DataRequired()])
	progress = SelectField('Current Progress', choices=[(0,"I haven't started"),
														(25,"I need to write an outline"),
														(50,'I have an outline'),
														(75, 'I have a draft')])
	submit = SubmitField('Create Project')

class DeleteForm(FlaskForm):
	password = PasswordField('Enter Your Password', validators=[DataRequired()])
	submit = SubmitField('Delete Project')

class IdeaEditorForm(FlaskForm):
	title = StringField('Topic')
	idea_freewrite = TextAreaField('Freewrite')
	idea_question = StringField('Question')
	submit = SubmitField('Save Idea')

app/project/__init__.py
from flask import Blueprint

project = Blueprint('project', __name__)

from . import views

app/project/views.py
from . import project
from flask_login import login_required, current_user
from flask import render_template, redirect, url_for, flash
from .forms import NewProjectForm, DeleteForm, IdeaEditorForm
from app.models import User, Project, Idea, Outline, Draft
from werkzeug.security import check_password_hash

from app import db

@project.route('/dashboard')
@login_required
def dashboard():
	projects = current_user.projects.all()
	return render_template('project/dashboard.html', projects=projects, title='Dashboard')

@project.route('/project_dashboard/<proj_id>')
@login_required
def project_dashboard(proj_id):
	project = Project.query.get(int(proj_id))

	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))

	return render_template('project/project_dashboard.html', project=project, title='Project Dashboard')

@project.route('/new_project', methods=['GET', 'POST'])
@login_required
def new_project():
	form = NewProjectForm()

	if form.validate_on_submit():
		project = Project(title=form.title.data, user_id=current_user.id, progress=form.progress.data)
		db.session.add(project)
		db.session.commit()

		return redirect(url_for('project.dashboard'))

	return render_template('project/new_project.html', form=form)

@project.route('/idea_editor/<proj_id>', methods=['GET', 'POST'])
@login_required
def idea_editor(proj_id):
	project = Project.query.get(int(proj_id))

	if current_user.id != project.user_id:
			return redirect(url_for('project.dashboard'))

	if project.ideas.first() == None:
		idea = Idea(user_id=current_user.id, project_id=project.id)
		db.session.add(idea)
		db.session.commit()
		return redirect(url_for('project.idea_editor', proj_id=project.id))

	idea = project.ideas.first()

	form = IdeaEditorForm()
	
	if form.validate_on_submit():
		idea.title = form.title.data
		idea.idea_freewrite = form.idea_freewrite.data
		idea.idea_question = form.idea_question.data
		flash('Idea Saved', 'success')
		db.session.commit()
		return redirect(url_for('project.project_dashboard', proj_id=project.id))
		
	return render_template('project/idea_editor.html', form=form, project=project, idea=idea)

@project.route('/outline_editor/<proj_id>', methods=['GET', 'POST'])
@login_required
def outline_editor(proj_id):
	project = Project.query.get(int(proj_id))

	if current_user.id != project.user_id:
			return redirect(url_for('project.dashboard'))

	if project.outlines.first() == None:
		outline = Outline(user_id=current_user.id, project_id=project.id)
		db.session.add(outline)
		db.session.commit()
		return redirect(url_for('project.outline_editor', proj_id=project.id))

	# form = OutlineEditorForm()

	outline = project.outlines.first()
	idea = project.ideas.first()

	if form.validate_on_submit():
		# code
		pass

	return render_template('project/outline_editor.html', form=form, project=project, idea=idea, outline=outline)

@project.route('/delete/type=<type>/id=<id>', methods=['GET', 'POST'])
@login_required
def delete(type, id):

	if type == 'project':
		project = Project.query.filter_by(id=id).first()
		if current_user.id != project.user_id:
			return redirect(url_for('project.dashboard'))
		item = Project.query.get(int(id))
	elif type == 'idea':
		idea = Idea.query.get(int(id))
		if current_user.id != idea.user_id:
			return redirect(url_for('project.dashboard'))
		item = Project.query.get(int(id))
	elif type == 'outline':
		outline = Outline.query.get(int(id))
		if current_user.id != outline.user_id:
			return redirect(url_for('project.dashboard'))
		item = Project.query.get(int(id))
	elif type == 'draft':
		draft = Draft.query.get(int(id))
		if current_user.id != draft.user_id:
			return redirect(url_for('project.dashboard'))
		item = Project.query.get(int(id))
	else:
		return redirect(url_for('project.dashboard'))

	form = DeleteForm()

	if form.validate_on_submit():
		if check_password_hash(current_user.password_hash, form.password.data):
			db.session.delete(item)
			db.session.commit()
			flash('Deleted Successfully', 'info')
			return redirect(url_for('project.dashboard'))

		else:
			flash('Password Incorrect', 'danger')

	return render_template('project/delete.html', item=item, form=form, title='Delete')

@project.route('/progress/<proj_id>', methods=['GET', 'POST'])
@login_required
def progress_project(proj_id):
	project = Project.query.get(int(proj_id))
	project.progress += 25
	db.session.commit()
	return redirect(url_for('project.project_dashboard', proj_id=proj_id))

app/templates/project/dashboard.html
{% extends 'base.html' %}


{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current='page'>Dashboard</li>
  </ol>
</nav>

<div class='container mt-5'>
	<div class='row'>
		<div class='col'></div>
		<div class='col-8'>
			<h1 class='display-4'>{{ current_user.first_name }}'s Current Projects</h1>
			<p>Open a Project or Create a <a href="{{ url_for('project.new_project') }}">New Project</a></p>
			<div class="list-group">
				{% for project in projects %}
			  	<a href="{{ url_for('project.project_dashboard', proj_id=project.id)}}" class="list-group-item list-group-item-action">{{ project.title }}</a>
			  	{% endfor %}
			</div>

		</div>
		<div class='col'></div>
	</div>
</div>

{% endblock content %}

app/templates/project/delete.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}


<div class='container mt-5'>
	<div class='row'>
		<div class='col-sm'></div>
		<div class='col-sm-6'>
			<p class='lead'>Are you sure you want to delete {{ item.title }}?</p>
			{{ wtf.quick_form(form, button_map={'submit':'btn btn-outline-danger'}) }}
		</div>
		<div class='col-sm'></div>
	</div>
</div>


{% endblock content %}

app/templates/project/idea_editor.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('project.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('project.project_dashboard', proj_id=project.id) }}">{{ project.title }}</a></li>
    <li class="breadcrumb-item active" aria-current='page'>Idea</li>
  </ol>
</nav>

<div class='container mt-5'>
	<div class='row'>
		<div class='col'></div>
		<div class='col-8'>
			<h1 class="text-center">{{ project.title }}</h1>
			<p class='lead text-center'>Idea Editor</p>
			<hr>
			<form action="" method="post">
				{{ form.hidden_tag() }}

				<div class="page page-1">
					<h4>Topic</h4>
					<p>Decide on a topic for your project. If you want to include sources into your project
					but haven't read any yet, go back and read before you begin writing. Describe what you
					are going to write about below. </p>
					
					<div class='form-group'>
			            {{ form.title(class='form-control', value=idea.title) }}
		       		</div>
		       		<button type='button' class='btn btn-outline-primary next-button' id='pg-1-next'>Next</button>
				</div>
				<div class="page page-2 form-group">
					<h4>Free Write</h4>
					<p>Write freely about your topic for 10 minutes. Try and write continuously. Don't 
					pay attention to grammar and spelling, and don't worry about editing what you wrote.
					Just try and get all of your ideas about your topic down on paper. If you use informaition
					from sources or find that you need to include more sources, indicate that in your writing </p>
					
					<div class='form-group'>
			            <textarea class="form-control" name="idea_freewrite" rows=10>{{ idea.idea_freewrite }}</textarea> 
		       		</div>
		       		<button type='button' class='btn btn-outline-primary prev-button' id='pg-2-prev'>Previous</button>
		       		<button type='button' class='btn btn-outline-primary next-button' id='pg-2-next'>Next</button>
				</div>
				<div class="page page-3 form-group">
					<h4>Question</h4>
					<p>Every piece of writing should answer a question. Now that you have gathered your 
					ideas and thought them through, decide on a question that you want your project to 
					answer. </p>
					
					<div class='form-group'>

			            {{ form.idea_question(class='form-control', value=idea.idea_question) }}<br>
			            <button type='button' class='btn btn-outline-primary prev-button' id='pg-3-prev'>Previous</button>
			            {{ form.submit(class='btn btn-outline-success')}}
		       		</div>

				</div>
			</form>
				
		</div>
		<div class='col'></div>
	</div>
</div>

<script type="text/javascript">
	var current_page = 1
	$( '.page' ).hide();
	$( '.page-1' ).show();

	$( '.next-button').click(function() {
		current_page++
		$( '.page' ).hide();
		$( '.page-'+current_page ).show()
	})

	$( '.prev-button').click(function() {
		current_page--
		$( '.page' ).hide();
		$( '.page-'+current_page ).show()
	})
	

    $('form input').keydown(function (e) {
        if (e.keyCode == 13) {
            e.preventDefault();
            return false;
        }
    });

</script>

{% endblock %}

app/templates/project/new_project.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class='container mt-5'>
    <div class='row'>
        <div class='col-sm'></div>
        <div class='col-sm'>
            <h1>Create New Project</h1>
            {{ wtf.quick_form(form, button_map={'submit': 'btn btn-outline-success'}) }}
        </div>
        <div class='col-sm'></div>
        
    </div>
    
</div>
{% endblock %}

app/templates/project/project_dashboard.html
{% extends 'base.html' %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('project.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current='page'>{{ project.title }}</li>
  </ol>
</nav>

<a href="{{ url_for('project.progress_project', proj_id=project.id) }}">Progress</a>
<div class='container mt-5'>
	<div class='row'>
		<div class='col'>
			<span>Actions</span><br>
			<small><a class='text-primary' href="{{ url_for('project.dashboard') }}">Return to Dashboard</a></small><br>
			<small><a class='text-danger' href="{{ url_for('project.delete', id=project.id, type='project') }}">Delete Project</a></small>
		</div>

		<div class='col-8'>
			<h1 class="text-center">{{ project.title }}</h1>
			<p class='lead text-center'>Project Dashboard</p>
			<hr>
			<h2> Your Progress: </h2><span id='progress' style='display: none;'>{{ project.progress }}</span>
			<div class="progress">
			  <div id='progress-bar' class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 0%; transition: none;"></div>
			</div>
			<div class="card mt-3" id='75'>
			  <div class="card-header">
			    Step 4
			  </div>
			  <div class="card-body">
			    <h5 class="card-title">Edit Your Draft</h5>
			    <p class="card-text">Recursively edit your drafts to build a well-crafted 
			    final draft</p>
			    {% if project.progress == 75 %}
			    <a href="{{ url_for('project.progress_project', proj_id=project.id) }}">I'm Done With This Step</a>
			    {% endif %}
			    <a href="#" class="btn btn-primary">Go somewhere</a>
			  </div>
			</div>
			
			<div class="card mt-3" id='50'>
			  <div class="card-header">
			    Step 3
			  </div>
			  <div class="card-body">
			    <h5 class="card-title">Write Your First Draft</h5>
			    <p class="card-text">Take all of the writing that you've done so far and turn it
			    into a workable first draft.</p>
			    
			    <a href="#" class="btn btn-primary">Go somewhere</a>
			    {% if project.progress == 75 and project.drafts.first() is not none %}
			    <a href="{{ url_for('project.progress_project', proj_id=project.id) }}" class='btn btn-outline-success'>I'm Done With This Step</a>
			    {% endif %}
			  </div>
			</div>
			
			<div class="card mt-3" id='25'>
			  <div class="card-header">
			    Step 2
			  </div>
			  <div class="card-body">
			    <h5 class="card-title">Create an Outline</h5>
			    <p class="card-text">Define a thesis or topic, outline your sub-sections, and 
			    formalize your argument.</p>
			    
			    <a href="{{ url_for('project.outline_editor', proj_id=project.id) }}" class="btn btn-primary">
			    	{% if project.outlines.first() is none %} Create Outline {% else %} Edit Outline{% endif %}
			    </a>
			    {% if project.progress == 25 and project.outlines.first() is not none %}
			    <a href="{{ url_for('project.progress_project', proj_id=project.id) }}" class='btn btn-outline-success'>I'm Done With This Step</a>
			    {% endif %}
			  </div>
			</div>
			<div class="card mt-3" id='0'>
			  <div class="card-header">
			    Step 1
			  </div>
			  <div class="card-body">
			    <h5 class="card-title">Come Up With a Topic</h5>
			    <p class="card-text">Start here. This tool will help you solidify your idea and 
			    put your thinking on paper.  </p>

			    <a href="{{ url_for('project.idea_editor', proj_id=project.id) }}" class="btn btn-primary">
			    	{% if project.ideas.first() is none %} Start Here {% else %} Edit Idea{% endif %}
				</a>
				{% if project.progress == 0 and project.ideas.first() is not none %}
			    <a href="{{ url_for('project.progress_project', proj_id=project.id) }}" class='btn btn-outline-success'>I'm Done With This Step</a>
			    {% endif %}
			  </div>
			</div>	
		</div>
		<div class='col'></div>
	</div>
</div>
<div class='mt-5'>
	
</div>

<style type="text/css">
	.hidden {
		display: none;
	}
</style>

<script type="text/javascript">
	var progress = $( '#progress' ).text()
	$( "#progress-bar" ).css("width",progress+'%')

	$( ".card" ).hide();
	$( "#"+progress ).show();
	$( "#"+progress ).addClass('border-primary');
	var m25 = parseInt(progress)-25;
	m25 = m25.toString();
	$( "#"+m25 ).show();
	var m50 = parseInt(progress)-50;
	m50 = m50.toString();
	$( "#"+m50 ).show();
	var m75 = parseInt(progress)-75;
	m75 = m75.toString();
	$( "#"+m75 ).show();
	var m100 = parseInt(progress)-100;
	m100 = m100.toString();
	$( "#"+m100 ).show();


</script>

{% endblock content %}